name: Check

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TERM: linux

jobs:
  check-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: make CC=gcc
      
    - name: Run check
      run: make check
  
  check-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: make CC=clang
      
    - name: Run check
      run: make check

  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run clang-format
      run: clang-format -n --Werror src/*.* src/tests/*.*
